### PR TITLE
Add Deploy to Fly.io

### PR DESCRIPTION
**Pull request by lubien**
Let me know if missed anything for this PR

### CODE REVIEW

**Comment by CommanderStorm** [comment]
- your configuration includes `min_machines_running = 1`. Does this mean >1 machines can be running on the same volume (this would likely corrupt sqlite)?
- (not required for merging)
  
  Given that you have knowlege about fly.io, could you have a look at
https://github.com/louislam/uptime-kuma/issues/4222 and if something jumps out at you?
  
  You have specified
  `auto_stop_machines = false` and `auto_start_machines = true`. Could this be a culprit in said issue?

**Comment by lubien** [comment]
> * your configuration includes `min_machines_running = 1`. Does this mean >1 machines can be running on the same volume (this would likely corrupt sqlite)?

Fly.io volumes are per machine so once it's attached you can attach the same volume to another one without some manual work. I used `min_machines_running = 1` just to be sure at least one machine is started but this might not be needed.

> * You have specified `auto_stop_machines = false` and `auto_start_machines = true` while @gridsystem has not. Could this be a culprit in said issue?

We dont auto stop / auto start machines unless these are set so it seems unlike. Ive checked their fly.toml and everything seems fine, including the volume. Im unsure about what could have been happening, specially on safari, if thats still an issue to them we'd probably want to take a look at their logs if possible. Im gonna watch the thread in case they come back.

**Comment by lubien** [comment]
> Hi @lubien I'm now on MacOS Sonoma 14.3.1 and Safari 17.3.1 with the same install of uptime kuma running on Fly, and steps to reproduce from my bug report still have the same result.
> 
> I'm slightly baffled as you say there shouldn't be anything wrong with my `fly.toml`. I will give yours a go when I get a minute or you're welcome to try mine too if you have time before me.
> 
> Do you have a link to a status page hosted on Fly which you could share with me to test?

Hi @gridsystem . Ive just restarted my uptime kuma machine and everything seems fine on either safari or not. 

For security reasons I prefer not to share my uptime kuma even if it's a new one, it simply has too much access, I hope you understand.

Since the issue is that your data is missing my guess is that this is volumes related. Can you reach out to https://community.fly.io/ and feel free to @ me there, Ill do my best to help

**Comment by CommanderStorm** [comment]
Have you contacted the fly.io support or asked in their forum as suggested here:
https://github.com/louislam/uptime-kuma/issues/4222#issuecomment-1950275615

Given that this configuration works for @lubien on safari, I don't know what could be different between your environments is.
In any case, I have no clue what is the difference between your environments (could be anything from arm/intel to the macOS version to fly.io changing something in their infrastructure).

**Comment by CommanderStorm** [comment]
> I’m not sure if @lubien has tried to reproduce the issue

Why are you suspecting that?
He has stated that `everything seems fine on either safari or not`.
Maybe you could screen record how you are reproducing the issue. There is clearly something different about your local/networking/server environments or testing methedologies.

> I doubt there is anything different in our setups as fly is configured in these short config files

I have seen many things that should not happen. Let's not rule out that the machines are behaving differently, perhaps because of a loose cables, a dying drive, a dying switch or network goblins on the way between the datacenter and your home.

=> perhaps you could use [`browserstack`](https://www.browserstack.com/test-on-mac-os) to rule out that your local environment is at fault.

> I’m not sure if anyone has tried to reproduce the issue

You are asking a really high bar here. I neither have a MacBook nor have ever used said hosting platform.
=> I think this issue would be better supported in the fly community forums. I don't know anything more in-depth about said platform (nor do the other devs AFAIK) and this is clearly a fly-problem (given that the demo site is working).

See the @lubien's comment from above:

> Since the issue is that your data is missing my guess is that this is volumes related. Can you reach out to https://community.fly.io/ and feel free to @ me there, Ill do my best to help

**Pull request merged**
